/** Short, practical facts shown when a challenge ends. */
export const SUGAR_FACTS: Record<number, { title: string; body: string }> = {
  1: { title: 'Một nấc nhỏ cũng có ý nghĩa', body: 'Nếu cùng một cỡ ly, đổi từ 100% xuống 70% đường có thể giảm khoảng 30% lượng đường được thêm vào. Hãy giữ thói quen kiểm tra tem ly.' },
  2: { title: 'Đường trong ly dễ bị đánh giá thấp', body: 'Một thìa cà phê đường khoảng 4 g. Hãy thử quy đổi lượng đường trên nhãn ra số thìa để dễ hình dung hơn.' },
  3: { title: 'Tên món không nói hết độ ngọt', body: 'Trà, cà phê và nước trái cây có thể chứa nhiều đường khi thêm siro, sữa đặc hoặc topping. Thành phần và cỡ ly mới giúp bạn đánh giá đúng.' },
  4: { title: 'Chia sẻ để cùng giữ nhịp', body: 'Một lời rủ uống ít đường có thể giúp bạn bè thử lựa chọn lành hơn mà không cần bỏ hẳn món yêu thích.' },
  5: { title: 'Mốc 50% là một bước tiến', body: 'Mức “50% đường” là mức tuỳ chỉnh của cửa hàng, không phải 50% tổng năng lượng. Cỡ ly và topping vẫn ảnh hưởng lượng đường thực tế.' },
  6: { title: 'Đọc nhãn theo khẩu phần', body: 'Khi so đồ uống, hãy đối chiếu cùng một lượng ml. Một chai lớn có thể chứa hơn một khẩu phần được ghi trên nhãn.' },
  7: { title: 'Ưu tiên phản xạ chọn ít ngọt', body: 'Khi cần quyết định nhanh, nước lọc hoặc trà không đường thường là lựa chọn đơn giản để tránh đường thêm vào.' },
  8: { title: 'Bạn đồng hành giúp thói quen bền hơn', body: 'Cùng một người bạn chọn đồ uống ít đường là cách dễ nhắc nhau mà không tạo cảm giác phải kiêng khem một mình.' },
  9: { title: 'Đường có nhiều tên trên nhãn', body: 'Sucrose, fructose, glucose và các loại siro đều là dạng đường. Hãy xem cả bảng dinh dưỡng và danh sách thành phần.' },
  10: { title: 'Tự pha giúp chủ động thành phần', body: 'Nước lọc thêm lát trái cây hoặc trà không đường tạo hương vị mà không cần siro. Hãy kiểm tra nguyên liệu trước khi pha.' },
  11: { title: 'Tên khác vẫn là đường', body: 'Các tên như maltose, dextrose và siro bắp có thể xuất hiện trong thành phần. Thứ tự nguyên liệu cho biết thành phần nào chiếm nhiều hơn.' },
  12: { title: 'Nhớ tên để nhận ra nhanh hơn', body: 'Nhận diện nhiều tên của đường giúp bạn đọc bảng thành phần chủ động hơn trong lần mua tiếp theo.' },
  13: { title: 'Mẹo nhỏ tạo thay đổi lớn', body: 'Giảm dần độ ngọt, đổi cỡ ly hoặc bỏ topping là những cách dễ thử khi cơn thèm ngọt xuất hiện.' },
  14: { title: 'Lắng nghe cơ thể mình', body: 'Mức tỉnh táo có thể thay đổi vì ngủ, vận động và ăn uống. Ghi lại cảm nhận giúp bạn nhìn xu hướng của bản thân qua thời gian.' },
  15: { title: 'Vị giác có thể thích nghi', body: 'Giảm độ ngọt dần dần có thể khiến mức ngọt cũ trở nên đậm hơn với bạn. Hãy chọn mức phù hợp và duy trì đều.' },
  16: { title: 'Đọc thành phần như giải mật mã', body: 'Nhiều tên đường có thể xuất hiện trong cùng một sản phẩm. Đọc tổng đường trên nhãn giúp bạn có bức tranh đầy đủ hơn.' },
  17: { title: 'Kiểm tra sự thật trước khi chọn', body: '“Tự nhiên” không đồng nghĩa với không có đường. Nước ép và mật ong vẫn góp phần vào tổng lượng đường bạn dùng.' },
  18: { title: 'Lựa chọn lành hơn vẫn cần xem nhãn', body: 'Đồ uống có hình trái cây hoặc nhãn “healthy” vẫn có thể được thêm đường. Hãy xem thành phần và khẩu phần.' },
  19: { title: 'Giữ đà đến chặng cuối', body: 'Điểm thưởng là một niềm vui; thói quen quan sát lượng đường trong đồ uống mới là thành quả bạn có thể mang theo lâu dài.' },
  20: { title: '0% đường thêm vào', body: 'Nước lọc, trà mộc và cà phê đen không thêm đường là lựa chọn dễ nhận biết. Với trà trái cây, hãy hỏi về siro và mật ngọt.' },
  21: { title: 'Hành trình vẫn tiếp tục', body: 'Sau 21 ngày, hãy giữ lại một thay đổi nhỏ mà bạn làm được đều đặn. Một lựa chọn ít ngọt hôm nay có thể trở thành thói quen ngày mai.' },
};
