// Toàn bộ chữ hiển thị nằm ở đây (không rải trong component) để team duyệt và sửa một chỗ.
// Các câu về sức khoẻ được đánh dấu [PHÁP LÝ] để nhờ người có chuyên môn xem lại trước khi launch.
export const vi = {
  app: { name: 'Level Down Challenge', tagline: '10 ngày bớt ngọt' },
  nav: { home: 'Hành trình', leaderboard: 'Xếp hạng', admin: 'Duyệt ảnh' },
  common: {
    loading: 'Đang tải…', retry: 'Thử lại', back: 'Quay lại', logout: 'Đăng xuất',
    genericError: 'Có lỗi xảy ra. Hãy thử lại.', save: 'Lưu', saved: 'Đã lưu', close: 'Đóng',
  },
  session: {
    signedInAs: (email: string) => `Đăng nhập: ${email}`,
    needLogin: 'Bạn cần đăng nhập để tiếp tục.',
    goLogin: 'Đăng nhập',
  },
  profile: {
    title: 'Hồ sơ', name: 'Tên hiển thị', avatar: 'Avatar', level: 'Mức đường ban đầu',
    save: 'Lưu thay đổi', saved: 'Đã lưu hồ sơ.', logout: 'Đăng xuất',
  },
  install: {
    hint: 'Mẹo: bấm "Chia sẻ → Thêm vào MH chính" để cài Level Down như một app.',
    dismiss: 'Đã hiểu',
  },
  journey: { title: 'MY SUGAR JOURNEY', unit: 'DAYS' },
  hero: { message: 'Cùng Gumi reset vị giác, cứu lấy động mạch!' /* [PHÁP LÝ] */ },
  day: { today: 'Hôm nay', done: 'Đã xong', open: 'Chưa làm', dying: 'Sắp mất chuỗi', missed: 'Đã lỡ', passed: 'Đã dùng Pass', rejected: 'Ảnh bị gỡ', future: 'Sắp tới', checked: 'Đã xong' },
  banners: {
    before: (date: string) => `Chiến dịch bắt đầu ngày ${date}. Hãy chuẩn bị hồ sơ nhé!`,
    dying: (hours: number) => `Gumi đang hấp hối! Bạn còn ${hours} giờ để dùng Sugar Pass cứu chuỗi.`,
    missedNoPass: 'Chuỗi đã đứt và bạn đã dùng hết Sugar Pass. Vẫn còn nhiều ngày để ghi điểm!',
    rejected: (reason: string) => `Ảnh của bạn bị gỡ: ${reason}. Bạn vẫn có thể dùng Sugar Pass nếu còn thời hạn.`,
    finished: 'Bạn đã tốt nghiệp 10 ngày bớt ngọt! Tải card khoe với bạn bè nhé.',
    ended: 'Chiến dịch đã kết thúc. Cảm ơn bạn đã đồng hành cùng Gumi!',
  },
  gumi: {
    bubbles: {
      bo_pho: ['Mình no đường quá…', 'Cho mình bớt ngọt nha!', 'Hôm nay bớt một nấc nhé?'],
      hap_hoi: ['Cứu mình bằng Sugar Pass!', 'X_X …'],
      tien_hoa: ['Chiến thần 0% đường!', 'Ngầu chưa?'],
    },
    caption: { bo_pho: 'Gumi bơ phờ', hap_hoi: 'Gumi đang hấp hối', tien_hoa: 'Gumi đã tiến hoá' },
  },
  pass: { button: 'Dùng Gumi Sugar Pass', title: 'Dùng Sugar Pass?', body: 'Ngày bị lỡ sẽ nhận 0 điểm nhiệm vụ nhưng chuỗi ngày của bạn được giữ. Bạn chỉ có 1 Pass.', confirm: 'Dùng Pass', cancel: 'Để sau', success: 'Gumi đã hồi sinh! Chuỗi của bạn được giữ.' },
  checkin: {
    title: 'Check-in bằng ảnh', pick: 'Chọn hoặc chụp ảnh', change: 'Đổi ảnh', level: 'Mức đường bạn đã uống', submit: 'Gửi check-in',
    uploading: 'Đang tải ảnh lên…', success: (pts: number) => `Xong! Bạn nhận +${pts} điểm.`,
    errors: { network: 'Mất kết nối. Ảnh của bạn vẫn được giữ, hãy thử lại.', notToday: 'Nhiệm vụ này không phải của hôm nay.', already: 'Bạn đã check-in ngày này rồi.', tooLarge: 'Ảnh quá lớn hoặc không phải ảnh. Hãy chọn ảnh khác.', level: 'Mức đường này không hợp lệ cho nhiệm vụ hôm nay.' },
    retry: 'Thử lại', back: 'Về hành trình',
  },
  leaderboard: {
    title: 'Sugar Slayer', me: 'Bạn', empty: 'Chưa có ai lên bảng. Hãy là người đầu tiên!', loading: 'Đang tải bảng xếp hạng…', error: 'Không tải được bảng xếp hạng.', retry: 'Thử lại',
    myRank: (rank: number, pts: number) => `Hạng hiện tại của bạn: #${rank} (${pts} pts)`,
    gap: (pts: number, name: string) => `Bạn chỉ cần thêm ${pts} điểm nữa để vượt qua ${name} và lọt vào Top 10!`,
    inTop: 'Bạn đang trong Top 10. Giữ vững phong độ nhé!',
  },
  onboarding: {
    title: 'Nhận nuôi Gumi', levelTitle: 'Mức đường hiện tại của bạn', drinksTitle: 'Số ly ngọt mỗi tuần', nameTitle: 'Tên hiển thị', avatarTitle: 'Chọn avatar',
    levels: { 100: { icon: '🧋', name: 'Hệ ngọt ngào', hint: '100% đường trở lên' }, 70: { icon: '🥤', name: 'Hệ lơ lửng', hint: '70% đường' }, 50: { icon: '🍵', name: 'Hệ trung dung', hint: '50% đường' } },
    estimate: (g: number, spoons: number) => `≈ ${g} g đường mỗi tuần (≈ ${spoons} thìa)`,
    nameHint: '2–30 ký tự', nameError: 'Tên cần từ 2 đến 30 ký tự.', submit: 'Nhận nuôi Gumi',
  },
  auth: {
    login: 'Đăng nhập', email: 'Email', password: 'Mật khẩu', submit: 'Đăng nhập', wrong: 'Email hoặc mật khẩu chưa đúng.', emailInvalid: 'Email chưa đúng định dạng.',
    forgot: 'Quên mật khẩu? Hãy nhắn cho ban tổ chức để được đặt lại.',
    inApp: 'Bạn đang mở trong ứng dụng nhúng (Zalo, Facebook…). Hãy mở bằng Chrome hoặc Safari để đăng nhập ổn định hơn.',
    consent: 'Bằng việc đăng ký, bạn đồng ý để ban tổ chức lưu và xem ảnh check-in của bạn trong thời gian chiến dịch.',
  },
  missions: [
    { day: 1, kind: 'DRINK', title: 'Bước Nhỏ Đầu Tiên', description: 'Hạ 1 nấc đường so với thói quen. Check-in ảnh tem ly hoặc hoá đơn.', points: 15 },
    { day: 2, kind: 'KNOW', title: 'Đoán Thìa Đoán Muỗng', description: 'Mini-quiz 5 câu: đoán số thìa đường trong đồ uống quen thuộc.', points: 10 },
    { day: 3, kind: 'DRINK', title: 'Nói Không Với Topping Ngọt', description: 'Chọn đồ uống không trân châu đen hoặc siro ngọt. Check-in ảnh ly.', points: 10 },
    { day: 4, kind: 'KNOW', title: 'Vạch Mặt Đường Ẩn', description: 'Tìm 3 cái tên "trá hình" của đường trên nhãn thành phần.', points: 10 },
    { day: 5, kind: 'SHARE', title: 'Khoe Ly Cùng Gumi', description: 'Chụp ly giảm đường và đăng Story kèm hashtag. Tải ảnh chụp màn hình lên.', points: 20 },
    { day: 6, kind: 'DRINK', title: 'Hạ Bậc Chạm Mốc 30%', description: 'Uống ở mức tối đa 30% đường. Check-in ảnh.', points: 20 },
    { day: 7, kind: 'KNOW', title: 'Emoji Catch', description: 'Giải mã 3 chuỗi emoji đồ uống nhiều đường và xem Sugar Crash là gì.', points: 10 },
    { day: 8, kind: 'SHARE', title: 'Buddy Challenge', description: 'Rủ một người bạn cùng uống giảm đường. Chụp ảnh hai ly cụng nhau.', points: 20 },
    { day: 9, kind: 'DRINK', title: 'Thanh Lọc Nguyên Bản', description: 'Uống một ly 0% đường: nước lọc, cold brew hoặc trà mộc. Check-in ảnh.', points: 25 },
    { day: 10, kind: 'FINAL', title: 'Lời Nhắn Tốt Nghiệp', description: 'Viết một câu cảm nhận gửi lên Bức tường cộng đồng của Gumi.', points: 15 },
  ],
  landing: {
    kicker: 'Sự kiện 10 ngày',
    title: 'Level Down Challenge',
    subtitle: '10 ngày cắt cơn nghiện ngọt — cùng Gumi reset vị giác, cứu lấy động mạch!' /* [PHÁP LÝ] */,
    bullets: [
      { icon: '🥤', text: 'Mỗi ngày 1 nhiệm vụ nhỏ: uống bớt ngọt, học mẹo, khoe bạn bè.' },
      { icon: '🔥', text: 'Tích điểm, giữ chuỗi, leo bảng xếp hạng Sugar Slayer.' },
      { icon: '🐱', text: 'Nuôi mèo Gumi từ bơ phờ vì đường tới chiến thần 0% đường.' },
    ],
    stats: { days: '10 ngày', players: '~100 người chơi', missions: '10 nhiệm vụ' },
    ctaPrimary: 'Bắt đầu — nhận nuôi Gumi',
    ctaSecondary: 'Mình đã có tài khoản',
    before: (date: string) => `Chiến dịch khởi động ngày ${date}. Đăng ký trước để không lỡ Day 1!`,
    running: (day: number) => `Chiến dịch đang ở Ngày ${day}/10. Vào trễ vẫn chơi được các ngày còn lại.`,
    ended: 'Mùa này đã khép lại. Cảm ơn bạn đã đồng hành cùng Gumi — hẹn gặp ở mùa sau!',
  },
  signup: {
    title: 'Tạo tài khoản',
    subtitle: 'Một tài khoản để lưu hành trình 10 ngày của bạn.',
    email: 'Email', password: 'Mật khẩu', confirm: 'Nhập lại mật khẩu',
    passwordHint: 'Ít nhất 8 ký tự.',
    submit: 'Đăng ký', haveAccount: 'Đã có tài khoản? Đăng nhập',
    errors: {
      email: 'Email chưa đúng định dạng.',
      passwordShort: 'Mật khẩu cần ít nhất 8 ký tự.',
      passwordMismatch: 'Hai lần nhập mật khẩu chưa khớp.',
      emailExists: 'Email này đã đăng ký. Bạn hãy đăng nhập nhé.',
    },
    consentLabel: 'Tôi đồng ý với điều khoản và việc xử lý ảnh check-in.',
    consentError: 'Bạn cần đồng ý điều khoản để tiếp tục.',
    readTerms: 'Đọc điều khoản đầy đủ',
  },
  terms: {
    title: 'Điều khoản & xử lý ảnh',
    consentAtSignup: 'Khi đăng ký, bạn đồng ý để ban tổ chức lưu và xem ảnh check-in của bạn trong thời gian chiến dịch, phục vụ chấm điểm và chống gian lận.',
    friendFaceNotice: '[PHÁP LÝ] Ngày 8 bạn có thể chụp ảnh cùng bạn bè. Hãy xin phép người trong ảnh trước khi đăng, và tránh để lộ thông tin nhạy cảm.',
    sections: [
      { h: 'Ảnh của bạn dùng vào việc gì', p: 'Ảnh check-in chỉ dùng để chấm điểm nhiệm vụ và hiển thị cho ban tổ chức. Ảnh không được công khai nếu bạn không tự đăng lên phần chia sẻ.' },
      { h: 'Ai xem được ảnh', p: 'Chỉ ban tổ chức chiến dịch. Ảnh được lưu ở kho riêng tư, không ai ngoài ban tổ chức truy cập được.' },
      { h: 'Lưu trong bao lâu', p: 'Ảnh được xoá trong vòng 30 ngày sau khi chiến dịch kết thúc, trừ khi bạn yêu cầu xoá sớm hơn.' },
      { h: 'Quyền của bạn', p: 'Bạn có thể yêu cầu xem hoặc xoá dữ liệu của mình bất cứ lúc nào bằng cách nhắn cho ban tổ chức.' },
    ],
    back: 'Quay lại',
  },
  quiz: {
    title: 'Ngày 2: Đoán Thìa Đoán Muỗng',
    intro: 'Kéo thanh trượt để đoán số thìa đường trong mỗi đồ uống. 5 câu, mỗi câu đúng gần +2 điểm.',
    start: 'Bắt đầu quiz',
    note: '[PHÁP LÝ] Số liệu đường là ước tính minh hoạ (PLACEHOLDER), cần chuyên môn dinh dưỡng xác nhận trước khi công bố.',
    questionOf: (i: number, total: number) => `Câu ${i}/${total}`,
    guessLabel: 'Bạn đoán:',
    spoons: (n: number) => `${n} thìa`,
    submit: 'Chốt đáp án', next: 'Câu tiếp', finish: 'Xem kết quả',
    answerWas: (n: number) => `Đáp án: ≈ ${n} thìa`,
    close: 'Sát ghê!', off: 'Hơi lệch nha!',
    result: (score: number, max: number) => `Bạn được ${score}/${max} điểm Sugar Quiz!`,
    resultSub: 'Càng đoán sát, điểm càng cao. Xem lại đáp án để nhớ lâu hơn.',
    already: 'Bạn đã làm quiz ngày này rồi.',
    notToday: 'Quiz này chỉ mở vào Ngày 2 của chiến dịch.',
    backHome: 'Về hành trình',
    questions: [
      { drink: 'Trà đào cam sả size L (100% đường)', answer: 10 },
      { drink: 'Trà sữa trân châu size M', answer: 12 },
      { drink: 'Cà phê sữa đá', answer: 6 },
      { drink: 'Nước ngọt có ga lon 330ml', answer: 9 },
      { drink: 'Sữa chua uống chai 200ml', answer: 5 },
    ],
  },
  day4: {
    title: 'Ngày 4: Vạch Mặt Đường Ẩn',
    intro: 'Trên nhãn thành phần bên dưới có 3 cái tên "trá hình" của đường. Tìm và chạm vào cả 3 trong 30 giây.',
    start: 'Bắt đầu (30 giây)',
    found: (n: number) => `Đã tìm: ${n}/3`,
    timeLeft: (s: number) => `Còn ${s}s`,
    label: 'Thành phần: Nước, HFCS, hương liệu tự nhiên, Maltodextrin, muối, chất ổn định, Dextrose, phẩm màu.',
    ingredients: ['Nước', 'HFCS', 'Hương liệu', 'Maltodextrin', 'Muối', 'Chất ổn định', 'Dextrose', 'Phẩm màu'],
    sugarNames: ['HFCS', 'Maltodextrin', 'Dextrose'],
    wrong: 'Cái này không phải đường. Nhìn kỹ lại nhé!',
    timeout: 'Hết giờ rồi! Đường ẩn rất giỏi trốn. Thử lại nào.',
    success: 'Tuyệt! Bạn đã vạch mặt cả 3 loại đường ẩn.',
    retry: 'Chơi lại', backHome: 'Về hành trình',
    crashInfo: '[PHÁP LÝ] HFCS, Maltodextrin, Dextrose đều là đường — thường bị giấu dưới tên lạ trên nhãn.',
  },
  day7: {
    title: 'Ngày 7: Emoji Catch',
    intro: 'Giải mã 3 chuỗi emoji thành tên đồ uống nhiều đường. Chọn đáp án đúng.',
    puzzleOf: (i: number, total: number) => `Chuỗi ${i}/${total}`,
    wrong: 'Chưa đúng, thử lại nhé!',
    success: 'Xong! Bạn giải được cả 3 chuỗi.',
    infographicTitle: 'Sugar Crash là gì?',
    infographic: '[PHÁP LÝ] Uống nhiều đường làm đường huyết tăng vọt rồi tụt nhanh, khiến bạn mệt, cáu và thèm ngọt tiếp — gọi là "sugar crash". Nội dung này cần chuyên môn y tế xác nhận.',
    backHome: 'Về hành trình',
    puzzles: [
      { emoji: '🧋⚫⚫⚫', options: ['Trà sữa trân châu', 'Cà phê đen', 'Nước lọc'], answer: 0 },
      { emoji: '🥤🍊➕🍬', options: ['Trà mộc', 'Soda cam ngọt', 'Trà đào ít đường'], answer: 1 },
      { emoji: '☕️🥛🍯', options: ['Cà phê sữa mật ong', 'Nước ép cần tây', 'Trà xanh không đường'], answer: 0 },
    ],
  },
  wall: {
    title: 'Ngày 10: Lời Nhắn Tốt Nghiệp',
    formPrompt: 'Viết một câu về việc cơ thể hoặc vị giác của bạn đã thay đổi ra sao sau 10 ngày.',
    placeholder: 'Ví dụ: Mình thấy nước lọc ngọt hơn và ngủ ngon hơn hẳn…',
    hint: '10–200 ký tự.',
    tooShort: 'Lời nhắn cần ít nhất 10 ký tự.',
    submit: 'Gửi lên bức tường',
    postedTitle: 'Đã gửi! Cảm ơn bạn đã đồng hành.',
    postedSub: 'Lời nhắn của bạn đã lên Bức tường cộng đồng Gumi.',
    wallTitle: 'Bức tường cộng đồng',
    empty: 'Chưa có lời nhắn nào. Hãy là người đầu tiên tốt nghiệp!',
    notToday: 'Bức tường tốt nghiệp mở vào Ngày 10.',
    viewCard: 'Xem card Sugar Journey',
    posts: [
      { name: 'Mai Anh', text: 'Mình bỏ được ly trà sữa mỗi chiều mà không thấy thèm nữa. Vị giác nhạy hơn thật!' },
      { name: 'Quang Huy', text: 'Cà phê giờ mình uống ít đường hẳn. Ngủ ngon hơn và bớt uể oải buổi chiều.' },
      { name: 'Bảo Ngọc', text: '10 ngày trôi nhanh ghê. Cảm ơn Gumi đã nhắc mình mỗi ngày!' },
    ],
  },
  summary: {
    title: 'Sugar Journey của bạn',
    graduated: '🎉 TỐT NGHIỆP 10 NGÀY BỚT NGỌT!',
    evolveCaption: 'Gumi đã tiến hoá: Chiến thần 0% đường',
    metrics: {
      sugarCut: 'Đường đã cắt giảm',
      grams: (g: number) => `≈ ${g} g`,
      spoons: (n: number) => `≈ ${n} thìa`,
      lowest: 'Mức đường thấp nhất chinh phục',
      healthy: 'Ly healthy đã check-in',
      quiz: 'Thần đồng Sugar Quiz',
      streak: 'Chuỗi ngày kiên trì',
    },
    totalPoints: 'Tổng điểm', rank: 'Hạng chung cuộc',
    provisional: 'Hạng tạm tính — bảng chốt sau khi hết chiến dịch.',
    final: 'Hạng chung cuộc đã chốt.',
    notEligible: 'Bạn cần hoàn thành đủ Ngày 10 để nhận card Sugar Journey.',
    download: 'Tải ảnh khoe Story / Facebook',
    downloaded: 'Đã tạo ảnh! Kiểm tra thư mục tải về của bạn.',
    downloadNote: '[PHÁP LÝ] Trên iPhone Safari, ảnh Story tạo bằng html-to-image đôi khi lỗi font/ảnh — cần người kiểm thử thật.',
    backHome: 'Về hành trình',
  },
  admin: {
    title: 'Duyệt ảnh check-in',
    tabByDay: 'Theo ngày', tabByUser: 'Theo người', tabFlags: 'Ảnh bị báo cáo',
    day: (n: number) => `Ngày ${n}`,
    approved: 'Đã duyệt', rejected: 'Đã gỡ', pending: 'Chờ',
    view: 'Xem', approve: 'Duyệt', reject: 'Gỡ ảnh',
    rejectTitle: 'Gỡ ảnh này?',
    rejectBody: 'Người chơi sẽ mất điểm ngày này và điểm, chuỗi được tính lại. Chọn lý do:',
    reasons: ['Ảnh không phải ly nước', 'Ảnh trùng ngày khác', 'Ảnh không rõ / không liên quan', 'Nghi ngờ chỉnh sửa'],
    confirmReject: 'Xác nhận gỡ', cancel: 'Huỷ',
    flagQueue: 'Hàng chờ ảnh bị báo cáo',
    flagReason: (r: string) => `Lý do báo cáo: ${r}`,
    empty: 'Không có ảnh nào cần duyệt.',
    forbiddenTitle: 'Không có quyền',
    forbidden: 'Trang này chỉ dành cho ban tổ chức. Nếu bạn nghĩ đây là nhầm lẫn, hãy liên hệ quản trị.',
  },
  errors: {
    notFoundTitle: 'Không tìm thấy trang',
    notFound: 'Đường dẫn này không tồn tại hoặc đã đổi. Hãy về hành trình của bạn.',
    offlineTitle: 'Mất kết nối',
    offline: 'Có vẻ bạn đang ngoại tuyến. Kiểm tra mạng rồi thử lại nhé.',
    maintenanceTitle: 'Đang bảo trì',
    maintenance: 'Gumi đang được chăm sóc một chút. Bạn quay lại sau ít phút nhé!',
    serverTitle: 'Có lỗi từ máy chủ',
    server: 'Máy chủ đang gặp sự cố. Việc của bạn không mất, hãy thử lại sau giây lát.',
    retry: 'Thử lại', home: 'Về hành trình',
  },
  toast: { success: 'Thành công', error: 'Có lỗi', info: 'Thông tin' },
} as const;

export type MissionKind = 'DRINK' | 'KNOW' | 'SHARE' | 'FINAL';
