// Toàn bộ chữ hiển thị nằm ở đây (không rải trong component) để team duyệt và sửa một chỗ.
// Nội dung sức khoẻ dùng giọng vui, gần gũi; số liệu đường/calo nên được người có chuyên môn dinh dưỡng rà lại trước khi launch.
// Bản 21 NGÀY — cốt truyện phiêu lưu 3 vùng đất, Gumi tiến hoá 4 nấc.

export type Speaker = 'gumi' | 'boss' | 'narrator';
export interface Line { who: Speaker; text: string }
export interface Chapter { day: number; intro: Line[]; win: Line[]; tease: string }

export const vi = {
  app: { name: 'Level Down Challenge', shortName: 'Level Down', tagline: 'Đường bớt một nấc, chất thêm một bậc' },
  nav: { home: 'Phòng Gumi', journey: 'Bản đồ', leaderboard: 'Xếp hạng', admin: 'Quản trị' },
  common: {
    loading: 'Đang tải…', retry: 'Thử lại', back: 'Quay lại', logout: 'Đăng xuất',
    genericError: 'Có lỗi xảy ra. Hãy thử lại.', save: 'Lưu', saved: 'Đã lưu', close: 'Đóng',
  },
  session: {
    signedInAs: (email: string) => `Đăng nhập: ${email}`,
    needLogin: 'Bạn cần đăng nhập để tiếp tục.',
    goLogin: 'Đăng nhập',
  },
  profile: {
    title: 'Hồ sơ', name: 'Tên hiển thị', avatar: 'Avatar', level: 'Mức đường ban đầu',
    save: 'Lưu thay đổi', saved: 'Đã lưu hồ sơ.', logout: 'Đăng xuất',
    password: {
      title: 'Đổi mật khẩu',
      hint: 'Nếu mật khẩu do ban tổ chức cấp, bạn nên đổi lại ngay cho an toàn.',
      current: 'Mật khẩu hiện tại',
      next: 'Mật khẩu mới',
      confirm: 'Nhập lại mật khẩu mới',
      submit: 'Cập nhật mật khẩu',
      changed: 'Đã đổi mật khẩu thành công.',
      wrongCurrent: 'Mật khẩu hiện tại chưa đúng.',
      short: 'Mật khẩu mới cần ít nhất 8 ký tự.',
      mismatch: 'Hai mật khẩu mới chưa khớp.',
      error: 'Không đổi được mật khẩu. Vui lòng thử lại.',
    },
  },
  install: {
    hint: 'Mẹo: bấm "Chia sẻ → Thêm vào MH chính" để cài Level Down như một app.',
    dismiss: 'Đã hiểu',
  },
  journey: {
    title: 'HÀNH TRÌNH CỦA BẠN', unit: 'NGÀY', total: 21, progress: (n: number) => `${n} / 21 NGÀY`,
    streakLabel: 'Chuỗi ngày', doneOf: (a: number, b: number) => `${a}/${b} ngày`,
    streakAria: (n: number) => `Bảng chuỗi ngày: đã giữ ${n} ngày`,
    nextBonus: (n: number, pts: number) => `Mốc ${n} ngày +${pts}đ`,
    allBonus: 'Đã đạt mọi mốc 🎉',
  },
  hero: { message: 'Đường bớt một nấc, chất thêm một bậc — cùng Gumi reset vị giác!' },
  day: { today: 'Hôm nay', done: 'Đã xong', open: 'Chưa làm', dying: 'Sắp mất chuỗi', missed: 'Đã lỡ', passed: 'Đã dùng Bùa', rejected: 'Ảnh bị gỡ', future: 'Sắp tới', checked: 'Đã xong' },

  map: {
    locked: 'Chưa mở',
    nodeAria: (day: number, title: string, state: string) => `Ngày ${day}: ${title} — ${state}`,
    actAria: (name: string) => `Vùng đất: ${name}`,
    dragHint: 'Kéo ngang để đi tiếp hành trình →',
  },

  banners: {
    before: (date: string) => `Hành trình bắt đầu ngày ${date}. Hãy chuẩn bị hồ sơ nhé!`,
    dying: (hours: number) => `Cơn Thèm vừa quật ngã Gumi — Sugar Crash! Bạn còn ${hours} giờ để dùng Bùa Hồi Sinh cứu chuỗi.`,
    missedNoPass: 'Chuỗi đã đứt và bạn đã dùng hết 3 Bùa Hồi Sinh. Vẫn còn nhiều ngày để ghi điểm!',
    rejected: (reason: string) => `Ảnh của bạn bị gỡ: ${reason}. Bạn vẫn có thể dùng Bùa Hồi Sinh nếu còn thời hạn.`,
    finished: 'Bạn đã tốt nghiệp 21 ngày bớt ngọt! Gumi tiến hoá thành Chiến Thần 0% Đường. Tải card khoe nào!',
    ended: 'Hành trình đã khép lại. Cảm ơn bạn đã đồng hành cùng Gumi!',
  },

  gumi: {
    bubbles: {
      bo_pho: ['Mình no đường quá…', 'Cho mình bớt ngọt nha!', 'Hôm nay bớt một nấc nhé?'],
      hap_hoi: ['Cứu mình bằng Bùa Hồi Sinh!', 'Cơn Thèm mạnh quá… X_X'],
      tien_hoa: ['Chiến thần 0% đường!', 'Boss Đường xong đời rồi!'],
    },
    caption: { bo_pho: 'Gumi bơ phờ', hap_hoi: 'Gumi bị Cơn Thèm quật ngã', tien_hoa: 'Gumi đã tiến hoá' },
    // 4 nấc tiến hoá theo hành trình + trạng thái gục ngã.
    stage: { crash: 'Sugar Crash (X_X)', sleepy: 'Sugar Sleepy', balanced: 'Sugar Balanced', charged: 'Sugar Charged', master: 'Sugar Master' },
  },

  wardrobe: {
    dock: 'Tủ đồ',
    title: 'Tủ đồ của Gumi',
    subtitle: 'Tự phối mũ, kính, khăn, màu lông và nền cho Gumi. Đi càng xa càng mở khoá nhiều món.',
    using: 'Đang dùng',
    reset: 'Về mặc định',
    locked: (n: number) => `Mở khoá khi xong ${n} ngày`,
    progress: (have: number, total: number) => `Đã mở khoá ${have}/${total} món`,
    close: 'Đóng',
  },

  pass: { button: 'Dùng Bùa Hồi Sinh', title: 'Bùa Hồi Sinh', body: 'Lỡ đúng 1 ngày thì chuỗi chưa đứt — dùng Bùa để nối lại (ngày đó 0 điểm nhưng chuỗi được giữ). Bạn có 3 Bùa cho cả hành trình.', confirm: 'Dùng Bùa cứu chuỗi', cancel: 'Để sau', gotIt: 'Đã hiểu', locked: 'Để dành nhé — Bùa chỉ dùng được khi Gumi hấp hối (bạn lỡ đúng 1 ngày).', count: (n: number) => `Còn ${n}/3 Bùa Hồi Sinh`, success: 'Gumi bật dậy! Chuỗi của bạn được giữ.',
    warnTitle: 'Gumi đang hấp hối! 😿',
    warnBody: (n: number) => `Bạn đang lỡ 1 ngày — vào chơi ngay sẽ MẤT chuỗi ${n} ngày. Dùng Bùa Hồi Sinh để giữ chuỗi nhé!`,
    warnBodyNoPass: 'Bạn đang lỡ 1 ngày và đã hết Bùa. Vào chơi sẽ bắt đầu lại chuỗi từ đầu.',
    playAnyway: 'Vẫn chơi (mất chuỗi)',
    rescuePlay: 'Cứu chuỗi rồi chơi' },

  // ——— CỐT TRUYỆN (viết như một cuộc phiêu lưu) ———
  story: {
    villain: { name: 'Boss Đường', alias: 'Cơn Thèm' },
    ui: {
      chapterOf: (day: number) => `CHƯƠNG ${day} / 21`,
      skip: 'Bỏ qua truyện',
      narrate: 'Nghe kể chuyện',
      narrateStop: 'Dừng đọc',
      startMission: 'Bắt đầu nhiệm vụ',
      backToMap: 'Về hành trình',
      tomorrow: 'Ngày mai',
      earned: (pts: number) => `+${pts} điểm`,
      speaker: { gumi: 'Gumi', boss: 'Boss Đường', narrator: '' } as Record<Speaker, string>,
    },
    // 3 vùng đất = 3 hồi, cũng là 3 nấc tiến hoá của Gumi.
    acts: [
      { n: 1, name: 'Đầm Lầy Ngọt', range: 'Ngày 1–7', icon: '🫧', blurb: 'Nơi Gumi chìm trong đường lỏng. Lội ra để tỉnh giấc — hoá Sugar Balanced.' },
      { n: 2, name: 'Rừng Đường Ẩn', range: 'Ngày 8–14', icon: '🌫️', blurb: 'Đường cải trang khắp lối. Vạch mặt chúng để nạp năng lượng — hoá Sugar Charged.' },
      { n: 3, name: 'Đỉnh 0%', range: 'Ngày 15–21', icon: '🏔️', blurb: 'Chặng leo cuối. Chạm mốc 0% và thức tỉnh thành Sugar Master — Chiến Thần 0% Đường.' },
    ],
    chapters: [
      { day: 1, intro: [
          { who: 'narrator', text: 'Màn sương ngọt tan dần. Gumi tỉnh dậy giữa Đầm Lầy Ngọt, bốn chân lún trong đường lỏng.' },
          { who: 'gumi', text: 'Người bạn ơi… mình kẹt ở đây bao lâu rồi? Kéo mình lên một nấc thôi, mình bước được!' },
        ], win: [ { who: 'gumi', text: 'Bước đầu tiên! Bùn ngọt vẫn níu chân, nhưng mình đã nhấc được rồi.' } ],
        tease: 'Gumi tập "đọc vị" kẻ thù — đo xem một ly nạp bao nhiêu đường.' },
      { day: 2, intro: [
          { who: 'gumi', text: 'Muốn thắng Boss thì phải biết hắn mạnh cỡ nào. Một ly quen thuộc… bao nhiêu thìa đường?' },
        ], win: [ { who: 'gumi', text: 'Nhiều hơn mình tưởng nhiều! Từ giờ mình nhìn ly nào cũng thấy con số.' } ],
        tease: 'Boss Đường tung ảo ảnh — đuổi hình bắt chữ để không bị lừa.' },
      { day: 3, intro: [
          { who: 'boss', text: 'Đố ngươi gọi đúng tên ta qua lớp nguỵ trang này~ 🧋' },
          { who: 'gumi', text: 'Trò này mình chơi được. Hiện nguyên hình đi, Đường!' },
        ], win: [ { who: 'gumi', text: 'Lột mặt nạ hết! Ảo ảnh của Boss không lừa được mình nữa.' } ],
        tease: 'Gumi cất tiếng gọi đồng minh khắp đầm lầy.' },
      { day: 4, intro: [
          { who: 'gumi', text: 'Một mình thì lâu ra khỏi đầm. Mình khoe ly hôm nay lên Story — ai nghe thấy thì cùng đi nào!' },
        ], win: [ { who: 'gumi', text: 'Có người thả tim, có người hỏi cách. Đội quân bớt ngọt đang lớn dần!' } ],
        tease: 'Thử bản lĩnh: hạ ly xuống mốc 50% đường.' },
      { day: 5, intro: [
          { who: 'narrator', text: 'Bùn ngọt đặc quánh níu từng bước.' },
          { who: 'gumi', text: 'Xuống 50% thôi. Nhạt hơn thật, nhưng đầu mình nhẹ bẫng!' },
        ], win: [ { who: 'gumi', text: 'Nửa lượng đường — nửa sức nặng. Bờ đầm đã hiện ra phía trước.' } ],
        tease: 'Đấu Trường Calo: xếp 5 ly theo độ ngọt.' },
      { day: 6, intro: [
          { who: 'boss', text: 'Ngươi có chắc biết ly nào ngọt hơn ly nào không?' },
          { who: 'gumi', text: 'Xếp từ nhạt tới gắt — để mình cho Boss xem mắt mình tinh cỡ nào.' },
        ], win: [ { who: 'gumi', text: 'Xếp chuẩn! Giờ nhìn thực đơn là mình biết chọn ly nào.' } ],
        tease: 'Cửa ải Đầm Lầy: một loạt câu hỏi chớp nhoáng chờ Gumi.' },
      { day: 7, intro: [
          { who: 'boss', text: 'Ải cuối của đầm lầy đây. Qua được thì ta trả tự do — mà ngươi qua không nổi đâu!' },
          { who: 'gumi', text: 'Bảy ngày rồi, mình khác xưa lắm. Xem mình bước qua ải này!' },
        ], win: [ { who: 'narrator', text: 'Ánh sáng bùng lên. Bụng Gumi nhẹ đi, mắt sáng lại — Sugar Sleepy hoá SUGAR BALANCED.' },
          { who: 'gumi', text: 'Mình ra khỏi Đầm Lầy Ngọt rồi! Nấc tiến hoá đầu tiên — cảm giác này đã ghê!' } ],
        tease: 'Vào Rừng Đường Ẩn — nơi đường cải trang tinh vi hơn.' },

      { day: 8, intro: [
          { who: 'narrator', text: 'Rừng Đường Ẩn mù sương, mỗi thân cây thì thầm mời gọi ngọt ngào.' },
          { who: 'gumi', text: 'Rủ thêm một buddy cho vững tâm. Hai đứa cụng ly, cùng tiến vào rừng!' },
        ], win: [ { who: 'gumi', text: 'Có đồng đội, rừng bớt đáng sợ hẳn. Cheers!' } ],
        tease: 'Truy tìm mật khẩu: những cái tên đường giấu trong ô chữ.' },
      { day: 9, intro: [
          { who: 'gumi', text: 'Boss giấu tên thật trong đám chữ này. Mình sẽ tìm ra hết!' },
        ], win: [ { who: 'gumi', text: 'Bắt được đủ mật khẩu! Rừng bớt một lớp sương.' } ],
        tease: 'Gạt cám dỗ topping — giữ ly thật thà.' },
      { day: 10, intro: [
          { who: 'boss', text: 'Thêm tí trân châu, tí kem cheese cho vui miệng nào~' },
          { who: 'gumi', text: 'Không topping ngọt hôm nay. Ly trơn mà lòng nhẹ.' },
        ], win: [ { who: 'gumi', text: 'Từ chối xong thấy… chẳng thèm thật. Lạ ghê!' } ],
        tease: 'Nhìn nhãn thành phần, gọi đúng tên đường ẩn.' },
      { day: 11, intro: [
          { who: 'narrator', text: 'Trên vỏ chai hiện ra những cái tên lạ hoắc: HFCS, Maltodextrin, Dextrose…' },
          { who: 'gumi', text: 'Đường à, đổi tên cũng vô ích. Mình gọi đúng mặt từng đứa!' },
        ], win: [ { who: 'gumi', text: 'Vạch mặt hết đường ẩn! Rừng này hết chỗ cho chúng trốn.' } ],
        tease: 'Lật thẻ trí nhớ: ghép đường với tên gọi trước khi hết giờ.' },
      { day: 12, intro: [
          { who: 'gumi', text: '30 giây, ghép đủ 5 cặp. Trí nhớ vị giác của mình, thử thách nào!' },
        ], win: [ { who: 'gumi', text: 'Ghép trọn bộ! Đầu mình giờ nhớ vị thật hơn vị ngọt.' } ],
        tease: 'Lan toả vị nhạt — kể cho cả rừng cùng nghe.' },
      { day: 13, intro: [
          { who: 'gumi', text: 'Điều tốt thì nên chia. Mình kể mẹo giảm đường cho mọi người!' },
        ], win: [ { who: 'gumi', text: 'Thêm vài người bảo "mình cũng thử". Tiếng lành lan trong rừng.' } ],
        tease: 'Cửa ải Rừng: lắng nghe chính cơ thể mình sau 2 tuần.' },
      { day: 14, intro: [
          { who: 'boss', text: 'Nửa đường rồi đấy… nhưng nửa sau mới là dốc dựng đứng!' },
          { who: 'gumi', text: 'Để mình xem cơ thể đã đổi tới đâu — rồi vượt ải này.' },
        ], win: [ { who: 'narrator', text: 'Một luồng năng lượng chạy dọc sống lưng Gumi — SUGAR BALANCED hoá SUGAR CHARGED!' },
          { who: 'gumi', text: 'Tỉnh táo hơn, nhẹ hơn, khoẻ hơn hẳn! Ra khỏi Rừng Đường Ẩn rồi!' } ],
        tease: 'Leo lên Đỉnh 0% — chặng cuối lạnh và trong veo.' },

      { day: 15, intro: [
          { who: 'narrator', text: 'Không khí trên Đỉnh 0% mỏng và mát. Từng hơi thở đều tỉnh táo.' },
          { who: 'gumi', text: 'Mốc 30% đường. Gần chạm số 0 rồi — cố lên nào!' },
        ], win: [ { who: 'gumi', text: '30% thôi mà vẫn ngon lành. Đỉnh không còn xa.' } ],
        tease: 'Vòng đấu chớp nhoáng: đuổi hình bắt chữ nâng cao.' },
      { day: 16, intro: [
          { who: 'boss', text: 'Lên cao rồi thì hoa mắt cho xem~' },
          { who: 'gumi', text: 'Mắt mình tinh hơn bao giờ hết. Ra hình đi Boss!' },
        ], win: [ { who: 'gumi', text: 'Giải hết! Gió đỉnh núi thổi bay chút cám dỗ cuối cùng.' } ],
        tease: 'Truy tìm sự thật: đúng hay sai về đường?' },
      { day: 17, intro: [
          { who: 'gumi', text: 'Đúng hay sai — giờ mình phân biệt được ngay. Kiểm tra nào!' },
        ], win: [ { who: 'gumi', text: 'Sự thật về đường, mình nắm rõ trong lòng bàn tay.' } ],
        tease: 'Ghép đôi những ly healthy — bộ sưu tập của nhà vô địch.' },
      { day: 18, intro: [
          { who: 'gumi', text: 'Toàn ly healthy mình từng uống. Ghép đôi hết trong 30 giây!' },
        ], win: [ { who: 'gumi', text: 'Trọn bộ healthy! Đây là gu mới của mình rồi.' } ],
        tease: 'Vòng quay may mắn tiếp sức trước ngày về đích.' },
      { day: 19, intro: [
          { who: 'narrator', text: 'Đỉnh núi hiện ra một bánh xe phát sáng.' },
          { who: 'gumi', text: 'Một cú quay lấy đà cho chặng cuối. Xin vía Gumi!' },
        ], win: [ { who: 'gumi', text: 'Được buff điểm rồi! Nạp năng lượng, tiến tới đỉnh!' } ],
        tease: 'Trận cuối: ly 0% nguyên bản, thuần khiết.' },
      { day: 20, intro: [
          { who: 'boss', text: 'Đừng… đừng chạm tới số 0! Ta van ngươi…' },
          { who: 'gumi', text: 'Một ly nước thật thà, 0% đường. Đây là đòn kết liễu, Boss.' },
        ], win: [ { who: 'gumi', text: 'Nước lọc mà mình thấy ngọt nhẹ! Vị giác đã reset hoàn toàn.' } ],
        tease: 'Đặt bút viết dòng cuối và bước lên đỉnh vinh quang.' },
      { day: 21, intro: [
          { who: 'boss', text: 'Không thể nào… ngươi đã hết cần tới ta!' },
          { who: 'gumi', text: 'Cảm ơn vì đã là kẻ thù xứng tầm. Nhưng từ đây, đường ai nấy đi.' },
          { who: 'narrator', text: 'Ánh sáng bùng nổ trên Đỉnh 0%. Kính râm hiện ra, thân hình rắn rỏi…' },
        ], win: [ { who: 'gumi', text: 'CHIẾN THẦN 0% ĐƯỜNG — Sugar Master đã thức tỉnh! 21 ngày, cảm ơn bạn đã dắt mình đi.' } ],
        tease: 'Viết một câu cảm nhận gửi lên Bức tường cộng đồng của Gumi nhé!' },
    ] as Chapter[],
  },

  // Trang "chạm để hoàn thành" cho các nhiệm vụ GAME/KNOW/TRACKER chưa có màn chơi riêng.
  tap: {
    badge: { GAME: '🎮 Thử tài', KNOW: '💡 Khám phá', TRACKER: '📈 Ghi nhận', SHARE: '📣 Lan toả', DRINK: '🥤 Uống', FINAL: '🎓 Tốt nghiệp' } as Record<string, string>,
    start: 'Hoàn thành nhiệm vụ',
    success: 'Tuyệt! Bạn đã hoàn thành nhiệm vụ hôm nay.',
    note: 'Bản demo: minigame đầy đủ sẽ được lắp ở bản chính thức. Bấm để hoàn thành và xem đoạn kết chương.',
    back: 'Về hành trình',
  },

  checkin: {
    title: 'Check-in bằng ảnh', pick: 'Chọn hoặc chụp ảnh', change: 'Đổi ảnh', level: 'Mức đường bạn đã uống', submit: 'Gửi check-in',
    uploading: 'Đang tải ảnh lên…', success: (pts: number) => `Xong! Bạn nhận +${pts} điểm.`,
    errors: { network: 'Mất kết nối. Ảnh của bạn vẫn được giữ, hãy thử lại.', notToday: 'Nhiệm vụ này không phải của hôm nay.', already: 'Bạn đã check-in ngày này rồi.', tooLarge: 'Ảnh quá lớn hoặc không phải ảnh. Hãy chọn ảnh khác.', level: 'Mức đường này không hợp lệ cho nhiệm vụ hôm nay.' },
    retry: 'Thử lại', back: 'Về hành trình',
    share: {
      heading: 'Chia sẻ lên Story',
      hint: 'Đăng ảnh lên Story kèm caption dưới đây (nhớ giữ hashtag & tag), rồi chụp màn hình Story tải lên làm bằng chứng.',
      caption: 'Mình đang thử thách 21 ngày bớt ngọt cùng Gumi 🐱🥤 Đường bớt một nấc, chất thêm một bậc!\n#LevelDownChallenge #GumiBotNgot #21NgayBotNgot @leveldown.challenge',
      shareBtn: '📤 Mở app chia sẻ',
      copyBtn: 'Sao chép caption',
      copied: '✓ Đã sao chép caption — dán vào Story nhé!',
      note: 'Instagram không nhận sẵn caption qua web nên app đã tự sao chép để bạn dán.',
    },
    ocr: {
      checking: (p: number) => `Đang kiểm tra ảnh (nhận diện ly nước + đọc tem)…${p > 0 ? ' ' + p + '%' : ''}`,
      okDrink: (what: string) => `Đã nhận diện ${what} trong ảnh ✔`,
      okStamp: 'Đã nhận diện tem/hoá đơn ly nước ✔',
      fail: 'Chưa nhận ra ly nước hay tem/hoá đơn trong ảnh. Hãy chụp rõ LY NƯỚC kèm tem/nhãn (tên đồ uống, size, % đường).',
      unavailable: 'Thiết bị này chưa chạy được bộ nhận diện. Bạn có thể gửi để ban tổ chức duyệt tay (ảnh giả sẽ bị loại và trừ điểm).',
      manual: 'Tôi xác nhận ảnh có ly nước / tem thật của tôi — gửi để ban tổ chức duyệt tay.',
      okVlm: (drink: string) => `Đã nhận diện: ${drink || 'đồ uống'} ✔`,
      sugarSeen: (pct: number) => `Nhãn ghi ~${pct}% đường`,
      sugarNone: 'Không đọc rõ % đường trên tem',
      declared: (pct: number) => `Bạn chọn ${pct}%`,
      sugarMismatch: 'Mức đường trên tem cao hơn mức bạn chọn — hãy chọn đúng để công bằng nhé.',
      vlmError: 'AI xác minh đang lỗi (mạng hoặc key). Hãy thử lại — không thể pass khi chưa xác minh được.',
      hint: '📸 Chụp thấy rõ LY NƯỚC hoặc tem/nhãn (tên, size, % đường) để Gumi ghi nhận nhé. Ảnh được kiểm tra ngay trên máy bạn, không gửi đi đâu cả.',
      retake: 'Chụp lại ảnh khác',
    },
    // Fallback khi AI không nhận diện được → gửi ban tổ chức duyệt tay.
    review: {
      cta: 'Nhờ ban tổ chức duyệt tay',
      sending: 'Đang gửi duyệt tay…',
      hint: 'AI chưa chắc chắn về ảnh này. Nếu đúng là ly/tem đồ uống thật của bạn, gửi để ban tổ chức duyệt tay (ảnh giả sẽ bị loại & trừ điểm).',
      pendingNote: 'Ảnh đã gửi ban tổ chức DUYỆT TAY. Bạn vẫn được ghi nhận ngày hôm nay trong lúc chờ — nếu ảnh không hợp lệ, ngày này sẽ bị gỡ.',
    },
  },
  leaderboard: {
    title: 'Sugar Slayer', me: 'Bạn', empty: 'Chưa có ai lên bảng. Hãy là người đầu tiên!', loading: 'Đang tải bảng xếp hạng…', error: 'Không tải được bảng xếp hạng.', retry: 'Thử lại',
    myRank: (rank: number, pts: number) => `Hạng hiện tại của bạn: #${rank} (${pts} pts)`,
    gap: (pts: number, name: string) => `Bạn chỉ cần thêm ${pts} điểm nữa để vượt qua ${name} và lọt vào Top 10!`,
    inTop: 'Bạn đang trong Top 10. Giữ vững phong độ nhé!',
    tiebreak: 'Hoà điểm: người chưa dùng Bùa Hồi Sinh được xếp trên.',
  },
  onboarding: {
    title: 'Nhận nuôi Gumi', levelTitle: 'Mức đường hiện tại của bạn', drinksTitle: 'Số ly ngọt mỗi tuần', nameTitle: 'Tên hiển thị', avatarTitle: 'Chọn avatar',
    levels: { 100: { icon: '🧋', name: 'Hệ ngọt ngào', hint: '100% đường trở lên' }, 70: { icon: '🥤', name: 'Hệ lơ lửng', hint: '70% đường' }, 50: { icon: '🍵', name: 'Hệ trung dung', hint: '50% đường' } },
    estimate: (g: number, spoons: number) => `≈ ${g} g đường mỗi tuần (≈ ${spoons} thìa)`,
    nameHint: '2–30 ký tự', nameError: 'Tên cần từ 2 đến 30 ký tự.', submit: 'Nhận nuôi Gumi',
  },
  auth: {
    login: 'Đăng nhập', welcome: 'Chào mừng trở lại', tagline: 'Gumi đang đợi bạn cùng vượt thử thách 21 ngày bớt ngọt 🐾', email: 'Email', password: 'Mật khẩu', submit: 'Đăng nhập', wrong: 'Email hoặc mật khẩu chưa đúng.', emailInvalid: 'Email chưa đúng định dạng.',
    google: 'Tiếp tục với Google', or: 'hoặc', googleError: 'Không đăng nhập được bằng Google. Hãy thử lại.',
    forgot: 'Quên mật khẩu?', noAccount: 'Chưa có tài khoản?', haveAccount: 'Đã có tài khoản?',
    inApp: 'Bạn đang mở trong ứng dụng nhúng (Zalo, Facebook…). Hãy mở bằng Chrome hoặc Safari để đăng nhập ổn định hơn.',
    consent: 'Bằng việc đăng ký, bạn đồng ý để ban tổ chức lưu và xem ảnh check-in của bạn trong thời gian chiến dịch.',
  },
  forgot: {
    title: 'Quên mật khẩu',
    tagline: 'Nhập email đăng ký, Gumi sẽ gửi link đặt lại mật khẩu cho bạn.',
    email: 'Email',
    submit: 'Gửi link đặt lại',
    emailInvalid: 'Email chưa đúng định dạng.',
    sentTitle: 'Đã gửi email!',
    sent: (email: string) => `Nếu ${email} là email đã đăng ký, bạn sẽ nhận được link đặt lại trong ít phút. Nhớ kiểm tra cả hộp thư Spam nhé.`,
    resend: 'Gửi lại',
    backToLogin: 'Về trang đăng nhập',
    error: 'Không gửi được email lúc này. Vui lòng thử lại sau giây lát.',
  },
  reset: {
    title: 'Đặt mật khẩu mới',
    tagline: 'Chọn một mật khẩu mới cho tài khoản của bạn.',
    password: 'Mật khẩu mới',
    confirm: 'Nhập lại mật khẩu',
    submit: 'Cập nhật mật khẩu',
    passwordShort: 'Mật khẩu cần ít nhất 8 ký tự.',
    passwordMismatch: 'Hai mật khẩu chưa khớp.',
    doneTitle: 'Đổi mật khẩu thành công!',
    done: 'Mật khẩu đã được cập nhật. Bạn có thể tiếp tục hành trình cùng Gumi.',
    goApp: 'Vào ứng dụng',
    invalidLink: 'Link đặt lại đã hết hạn hoặc không hợp lệ. Hãy yêu cầu gửi lại từ trang Quên mật khẩu.',
    requestNew: 'Yêu cầu link mới',
    error: 'Không cập nhật được mật khẩu. Vui lòng thử lại.',
  },
  missions: [
    { day: 1, kind: 'DRINK', title: 'Bước Nhỏ Đầu Tiên', description: 'Hạ 1 nấc đường so với thói quen (VD: 100% xuống 70%). Chụp tem ly, hoá đơn hoặc ly nước giảm đường.', points: 15 },
    { day: 2, kind: 'KNOW', title: 'Đoán Thìa Đoán Muỗng', description: 'Mini-quiz: đoán số thìa đường trong đồ uống quen thuộc.', points: 10 },
    { day: 3, kind: 'GAME', title: 'Đuổi Hình Bắt Chữ', description: 'Ghép 2 hình đoán tên đồ uống (Trà Thái · Cam vắt · Sữa gạo), đúng thì mở khoá sự thật về đường & calo.', points: 15 },
    { day: 4, kind: 'SHARE', title: 'Khoe Ly Cùng Gumi', description: 'Chụp ly giảm đường, đăng Story kèm hashtag và tag fanpage dự án. Tải ảnh chụp màn hình Story lên.', points: 20 },
    { day: 5, kind: 'DRINK', title: 'Chạm Mốc 50% Đường', description: 'Uống ly tối đa 50% đường (hoặc cà phê ít sữa/ít đường). Check-in ảnh.', points: 20 },
    { day: 6, kind: 'GAME', title: 'Đấu Trường Calo', description: 'Sắp xếp 5 đồ uống từ ít đường nhất → nhiều đường nhất (2 lượt).', points: 20 },
    { day: 7, kind: 'GAME', title: 'Bay Qua Cơn Thèm', description: 'CỬA ẢI Hồi 1 — Flappy Bird: lách qua mỗi cột đường +1 điểm, đạt tối đa 50 điểm để hạ Boss Cơn Thèm.', points: 30 },
    { day: 8, kind: 'SHARE', title: 'Buddy Challenge', description: 'Rủ một người bạn cùng uống ly ít đường. Chụp ảnh hai ly "cheers".', points: 20 },
    { day: 9, kind: 'GAME', title: 'Truy Tìm Mật Khẩu', description: 'Wordsearch: tìm 5 cái tên đường ẩn trong ô chữ (+10/key).', points: 50 },
    { day: 10, kind: 'DRINK', title: 'DIY Drink', description: 'Tự chuẩn bị bình nước mang đi học hoặc đi làm: nước lọc thả lát trái cây, bạc hà hoặc trà túi lọc không đường. Tải ảnh bình nước lên.', points: 20 },
    { day: 11, kind: 'KNOW', title: 'Vạch Mặt Đường Ẩn', description: 'Nhìn bảng thành phần và gọi đúng tên đường trên nhãn.', points: 10 },
    { day: 12, kind: 'GAME', title: 'Lật Thẻ Trí Nhớ', description: 'Lật 10 thẻ, ghép 5 cặp đường ↔ tên gọi trong 30 giây (+10/cặp).', points: 50 },
    { day: 13, kind: 'SHARE', title: 'Mẹo Nhỏ Cắt Đường', description: 'Chia sẻ một mẹo giúp bạn vượt qua cơn thèm ngọt lên Story, rồi tải ảnh chụp Story lên.', points: 20 },
    { day: 14, kind: 'GAME', title: 'Đánh Bại Boss Đường', description: 'CỬA ẢI Hồi 2 — hứng nước lành 💧🍵 để pha loãng độ ngọt của Boss, né đường xấu 🧊🥤🍬. Còn 3 mạng.', points: 10 },
    { day: 15, kind: 'DRINK', title: 'Chạm Mốc 30% Đường', description: 'Check-in ly giảm đường mức 30% (hoặc nước tự pha không đường). Check-in ảnh.', points: 20 },
    { day: 16, kind: 'GAME', title: 'Gumi Bắt Chữ', description: 'Crossword: đoán từ khoá mỗi dòng (tên các loại đường ẩn) theo gợi ý, trong 3 phút.', points: 40 },
    { day: 17, kind: 'KNOW', title: 'Truy Tìm Sự Thật', description: '5 câu đúng/sai nhanh về đường (+5/câu).', points: 25 },
    { day: 18, kind: 'GAME', title: 'Ghép Đôi Healthy', description: 'Lật 10 thẻ, ghép 5 cặp đồ uống ít đường trong 30 giây (+10/cặp).', points: 50 },
    { day: 19, kind: 'GAME', title: 'Vòng Quay May Mắn', description: 'Quay vòng nhận buff điểm ngẫu nhiên (+10 đến +30) trước ngày về đích.', points: 20 },
    { day: 20, kind: 'DRINK', title: 'Thanh Lọc Nguyên Bản', description: 'Ly 0% đường: nước lọc, cold brew, trà mộc hoặc trà trái cây nguyên bản. Check-in ảnh.', points: 20 },
    { day: 21, kind: 'FINAL', title: 'Giải Cứu Gumi & Lời Nhắn Tốt Nghiệp', description: 'Giải màn Neko Slide, viết lời cảm nhận gửi lên Bức tường Gumi (+15). Có ảnh chia sẻ Story được cộng thêm 10 điểm.', points: 15 },
  ],
  landing: {
    kicker: 'Hành trình 21 ngày',
    title: 'Level Down Challenge',
    subtitle: 'Đường bớt một nấc, chất thêm một bậc — 21 ngày cùng Gumi reset vị giác!',
    bullets: [
      { icon: 'map', text: 'Đi qua 3 vùng đất, mỗi ngày một chương truyện và một thử thách nhỏ.' },
      { icon: 'flame', text: 'Tích điểm, giữ chuỗi, vượt cửa ải để leo bảng xếp hạng Sugar Slayer.' },
      { icon: 'sparkle', text: 'Nuôi Gumi tiến hoá qua 4 nấc: Sleepy → Balanced → Charged → Master.' },
    ],
    stats: { days: '21 ngày', players: '~100 người chơi', missions: '3 vùng đất' },
    ctaPrimary: 'Bắt đầu — nhận nuôi Gumi',
    ctaSecondary: 'Mình đã có tài khoản',
    before: (date: string) => `Hành trình khởi động ngày ${date}. Đăng ký trước để không lỡ Ngày 1!`,
    running: (day: number) => `Hành trình đang ở Ngày ${day}/21. Vào trễ vẫn chơi được các ngày còn lại.`,
    personal: 'Ngày bạn tham gia chính là Ngày 1 — bắt đầu bất cứ lúc nào, đi hết 21 ngày theo nhịp của riêng bạn!',
    ended: 'Mùa này đã khép lại. Cảm ơn bạn đã đồng hành cùng Gumi — hẹn gặp ở mùa sau!',
  },
  signup: {
    title: 'Tạo tài khoản',
    subtitle: 'Một tài khoản để lưu hành trình 21 ngày của bạn.',
    email: 'Email', password: 'Mật khẩu', confirm: 'Nhập lại mật khẩu',
    passwordHint: 'Ít nhất 8 ký tự.',
    submit: 'Đăng ký', haveAccount: 'Đã có tài khoản? Đăng nhập',
    errors: {
      email: 'Email chưa đúng định dạng.',
      passwordShort: 'Mật khẩu cần ít nhất 8 ký tự.',
      passwordMismatch: 'Hai lần nhập mật khẩu chưa khớp.',
      emailExists: 'Email này đã đăng ký. Bạn hãy đăng nhập nhé.',
    },
    consentLabel: 'Tôi đồng ý với điều khoản và việc xử lý ảnh check-in.',
    consentError: 'Bạn cần đồng ý điều khoản để tiếp tục.',
    readTerms: 'Đọc điều khoản đầy đủ',
  },
  terms: {
    title: 'Điều khoản & xử lý ảnh',
    consentAtSignup: 'Khi đăng ký, bạn đồng ý để ban tổ chức lưu và xem ảnh check-in của bạn trong thời gian chiến dịch, phục vụ chấm điểm và chống gian lận.',
    friendFaceNotice: '👯 Rủ bạn cùng "cheers" ly ít đường nào! Nhớ xin phép người trong ảnh trước khi đăng nhé.',
    sections: [
      { h: 'Ảnh của bạn dùng vào việc gì', p: 'Ảnh check-in chỉ dùng để chấm điểm nhiệm vụ và hiển thị cho ban tổ chức. Ảnh không được công khai nếu bạn không tự đăng lên phần chia sẻ.' },
      { h: 'Ai xem được ảnh', p: 'Chỉ ban tổ chức chiến dịch. Ảnh được lưu ở kho riêng tư, không ai ngoài ban tổ chức truy cập được.' },
      { h: 'Lưu trong bao lâu', p: 'Ảnh được xoá trong vòng 30 ngày sau khi chiến dịch kết thúc, trừ khi bạn yêu cầu xoá sớm hơn.' },
      { h: 'Quyền của bạn', p: 'Bạn có thể yêu cầu xem hoặc xoá dữ liệu của mình bất cứ lúc nào bằng cách nhắn cho ban tổ chức.' },
    ],
    back: 'Quay lại',
  },
  quiz: {
    title: 'Ngày 2: Đoán Thìa Đoán Muỗng',
    intro: 'Kéo thanh trượt để đoán số thìa (muỗng cà phê) đường trong 1 ly trà sữa. Đoán trúng khoảng 12–15 là chuẩn nhất!',
    start: 'Bắt đầu',
    note: '🧋 Biết không? Một ly trà sữa có thể "giấu" nhiều đường hơn cả một lon nước ngọt đó — thử đoán xem bao nhiêu thìa nhé!',
    question: 'Theo bạn, trong 1 ly trà sữa có thể chứa bao nhiêu thìa đường?',
    guessLabel: 'Bạn đoán:',
    spoons: (n: number) => `${n} thìa`,
    submit: 'Chốt đáp án',
    // Khoảng đúng: 12–15 muỗng cà phê (~50g–60g đường).
    correctMin: 12,
    correctMax: 15,
    correct: 'Chính xác! 🎉',
    off: 'Hơi lệch nha — đáp án nằm trong khoảng 12–15 thìa.',
    answerWas: 'Đáp án: khoảng 12–15 thìa (≈ 50g – 60g đường).',
    explain:
      'Một ly trà sữa thông thường có thể chứa từ 12 đến 15 muỗng đường (tương đương khoảng 50g – 60g đường). Con số này thường vượt quá lượng đường tiêu thụ tối đa được khuyến nghị trong cả một ngày.',
    result: (score: number, max: number) => `Bạn được ${score}/${max} điểm Sugar Quiz!`,
    resultSub: 'Nhớ con số này để lần sau gọi "ít đường" cho nhẹ bụng nha.',
    already: 'Bạn đã làm quiz ngày này rồi.',
    notToday: 'Quiz này chỉ mở vào Ngày 2 của chiến dịch.',
    backHome: 'Về hành trình',
  },
  day4: {
    title: 'Ngày 11: Vạch Mặt Đường Ẩn',
    intro: 'Trên nhãn thành phần bên dưới có 3 cái tên "trá hình" của đường. Tìm và chạm vào cả 3 trong 30 giây.',
    start: 'Bắt đầu (30 giây)',
    found: (n: number) => `Đã tìm: ${n}/3`,
    timeLeft: (s: number) => `Còn ${s}s`,
    label: 'Thành phần: Nước, HFCS, hương liệu tự nhiên, Maltodextrin, muối, chất ổn định, Dextrose, phẩm màu.',
    ingredients: ['Nước', 'HFCS', 'Hương liệu', 'Maltodextrin', 'Muối', 'Chất ổn định', 'Dextrose', 'Phẩm màu'],
    sugarNames: ['HFCS', 'Maltodextrin', 'Dextrose'],
    wrong: 'Cái này không phải đường. Nhìn kỹ lại nhé!',
    timeout: 'Hết giờ rồi! Đường ẩn rất giỏi trốn. Thử lại nào.',
    success: 'Tuyệt! Bạn đã vạch mặt cả 3 loại đường ẩn.',
    retry: 'Chơi lại', backHome: 'Về hành trình',
    crashInfo: '🕵️ HFCS, Maltodextrin, Dextrose… nghe như tên hoá chất nhưng đều là ĐƯỜNG "đội lốt" trên nhãn đó!',
  },
  // Ngày 3 — Vén Màn 3 Ly Nước: chạm mở từng ly để đọc sự thật về đường/calo.
  day3: {
    title: 'Ngày 3: Đuổi Hình Bắt Chữ',
    intro: 'Ghép 2 hình lại thành tên một đồ uống. Đoán đúng để mở khoá sự thật về đường & calo của ly đó!',
    guessPrompt: 'Ghép 2 hình — đây là món gì?',
    puzzleOf: (i: number, total: number) => `Hình ${i}/${total}`,
    wrong: 'Chưa đúng, nhìn kỹ 2 hình ghép lại nhé!',
    revealTitle: 'Bắt chữ chuẩn! Sự thật về ly này:',
    next: 'Hình tiếp theo →',
    finish: 'Hoàn thành',
    success: 'Bạn đã "đọc vị" cả 3 ly — giờ order thức uống là biết chọn cho khéo rồi!',
    note: '💡 Mẹo nhỏ: tên đồ uống chưa cho biết lượng đường. Hãy hỏi mức đường thêm vào và xem cỡ ly trước khi chọn.',
    backHome: 'Về hành trình',
    cards: [
      {
        emoji: '🧋',
        name: 'Trà Thái',
        tag: 'Cân nhắc lượng đường',
        tone: 'warn' as const,
        points: [
          { h: 'Độ ngọt thay đổi theo công thức', p: 'Trà Thái có thể được thêm sữa đặc, siro hoặc đường. Lượng đường thay đổi theo cỡ ly và cách pha.' },
          { h: 'Đừng đoán từ màu sắc', p: 'Màu sắc không cho biết ly chứa bao nhiêu đường. Hãy xem tem ly hoặc hỏi nhân viên về mức đường.' },
          { h: 'Cách giảm ngọt', p: 'Chọn cỡ ly nhỏ hơn và yêu cầu giảm đường hoặc bớt sữa đặc nếu cửa hàng hỗ trợ.' },
        ],
      },
      {
        emoji: '🍊',
        name: 'Cam Vắt',
        tag: 'Xem đường thêm vào',
        tone: 'good' as const,
        points: [
          { h: 'Vẫn có đường tự nhiên', p: 'Cam vắt nguyên chất có đường từ trái cây. Khi thêm đường hoặc siro, lượng đường trong ly tăng thêm.' },
          { h: 'Chất xơ ở đâu?', p: 'Ăn cam nguyên quả thường giữ được nhiều chất xơ hơn uống nước ép đã lọc bã.' },
          { h: 'Cách gọi ly', p: 'Nếu chọn cam vắt, hãy thử gọi không thêm đường và chọn cỡ ly vừa phải.' },
        ],
      },
      {
        emoji: '🥛',
        name: 'Sữa Gạo',
        tag: 'Đọc thành phần',
        tone: 'good' as const,
        points: [
          { h: 'Có thể được thêm đường', p: 'Sữa gạo đóng chai hoặc pha tại quán có thể chứa đường thêm vào. Hãy kiểm tra nhãn hoặc hỏi công thức.' },
          { h: 'Kiểm tra loại sữa', p: 'Một số sản phẩm pha thêm sữa bò. Nếu bạn cần tránh lactose, hãy đọc danh sách thành phần.' },
          { h: 'Cách chọn', p: 'Ưu tiên loại không thêm đường hoặc yêu cầu giảm ngọt khi đặt món.' },
        ],
      },
    ],
  },
  // ——— MINIGAME cho các ngày GAME/KNOW/TRACKER (thay cho màn "chạm để hoàn thành") ———
  minigames: {
    common: {
      start: 'Bắt đầu',
      retry: 'Chơi lại',
      backHome: 'Về bản đồ',
      backToRoom: 'Về phòng Gumi',
      check: 'Kiểm tra',
      wrong: 'Chưa đúng, thử lại nhé!',
      correct: 'Chuẩn luôn!',
      timeUp: 'Hết giờ rồi!',
      timeUpQuiz: 'Hết giờ! Đáp án đúng đang sáng màu xanh.',
      timeUpMemory: (n: number, total: number) => `Hết 30 giây — bạn ghép được ${n}/${total} cặp. Cửa ải tính giờ không cho chơi lại, hẹn Gumi ở chặng sau nhé!`,
    },
    // Ngày 6 — Đấu Trường Calo: xếp 5 ly theo độ ngọt.
    sort: {
      title: 'Ngày 6: Đấu Trường Calo',
      intro: 'Kéo-thả 5 đồ uống từ ÍT đường nhất (trên cùng) đến NHIỀU đường nhất (dưới cùng) rồi bấm Kiểm tra. Bạn chỉ có 2 lượt!',
      label: 'Ít đường ↑ · Nhiều đường ↓',
      wrong: 'Thứ tự chưa đúng. Ngẫm lại độ ngọt rồi thử tiếp nhé!',
      tries: (left: number) => `Còn ${left} lượt`,
      lastTry: 'Lượt cuối rồi — ngẫm kỹ nhé!',
      outOfTries: 'Hết 2 lượt xếp rồi!',
      outOfTriesSub: 'Cửa ải này chỉ cho 2 lượt Kiểm tra — hẹn Gumi ở chặng sau nhé!',
      success: 'Xếp chuẩn! Giờ nhìn thực đơn là bạn biết ngay ly nào ngọt hơn.',
      // Ít đường (trên) → nhiều đường (dưới): Cold Brew 0g · Trà tắc ~30-35g · Trà đào cam sả ~35g · Sữa tươi TC đường đen ~40-45g · Trà sữa TC ~55-60g
      order: ['Cold Brew (trà ủ lạnh)', 'Trà tắc', 'Trà đào cam sả', 'Sữa tươi trân châu đường đen', 'Trà sữa trân châu truyền thống'],
    },
    // Ngày 9 — Truy Tìm Mật Khẩu (word search): giải 5 gợi ý, bắt đúng 5 "mật khẩu" ẩn giữa đám chữ.
    wordHunt: {
      title: 'Ngày 9: Truy Tìm Mật Khẩu',
      intro: 'Boss giấu 5 mật khẩu trong lưới chữ (ngang · dọc · chéo). Chạm ô ĐẦU rồi ô CUỐI của từ để bắt. Đọc gợi ý bên dưới nhé!',
      cluesTitle: '5 gợi ý',
      found: (n: number, total: number) => `Đã bắt: ${n}/${total}`,
      wrong: 'Chưa đúng — đọc lại gợi ý rồi thử tiếp nhé!',
      success: 'Phá mật khẩu thành công! Bạn đã tìm đủ 5 từ khoá.',
      note: '🕵️ Đường không chỉ làm tăng cân — nó âm thầm "tấn công" gan, da (collagen) và tế bào, đẩy nhanh lão hoá. Bắt đủ 5 mật khẩu nào!',
      clues: [
        'Cơ quan lọc đường và chuyển đường thừa thành mỡ nội tạng?',
        'Quá trình suy giảm chức năng tế bào theo thời gian, bị đường đẩy nhanh?',
        'Đơn vị cấu tạo nên cơ thể sống, dễ bị đường làm tổn thương?',
        'Loại protein chiếm 70% cấu trúc da, bị đường bẻ gãy?',
        'Đồ uống ngọt dạng lỏng của giới trẻ, chứa nhiều đường nhất?',
      ],
      words: ['GAN', 'LÃO HÓA', 'TẾ BÀO', 'COLLAGEN', 'TRÀ SỮA', 'THẬN', 'VITAMIN', 'CHẤT XƠ', 'NƯỚC LỌC', 'CAFFEINE', 'CANXI', 'CHẤT ĐẠM'],
      sugars: ['GAN', 'LÃO HÓA', 'TẾ BÀO', 'COLLAGEN', 'TRÀ SỮA'],
    },
    // Ngày 12 & 18 — Lật thẻ trí nhớ (ghép cặp).
    memory12: {
      title: 'Ngày 12: Lật Thẻ Trí Nhớ',
      intro: 'Lật 10 thẻ và ghép mỗi loại đường với tên gọi của nó trong 30 giây. Ghép đủ 5 cặp!',
      success: 'Ghép trọn bộ! Đầu bạn giờ nhớ vị thật hơn vị ngọt.',
      pairs: [
        { a: 'Glucose', b: 'Đường đơn' },
        { a: 'Fructose', b: 'Đường trái cây' },
        { a: 'Sucrose', b: 'Đường mía / đường kính' },
        { a: 'Maltose', b: 'Đường mạch nha' },
        { a: 'Lactose', b: 'Đường sữa' },
      ],
    },
    memory18: {
      title: 'Ngày 18: Ghép Đôi Healthy',
      intro: 'Lật 10 thẻ và ghép 5 cặp ly nước ít đường giống nhau trong 30 giây. Ghi nhớ vị trí nhé!',
      success: 'Trọn bộ healthy! Đây là gu mới của bạn rồi.',
      pairs: [
        { a: '🌼 Trà hoa cúc', b: '🌼 Trà hoa cúc' },
        { a: '🥤 Nước detox', b: '🥤 Nước detox' },
        { a: '🥥 Nước dừa tươi', b: '🥥 Nước dừa tươi' },
        { a: '🧃 Nước ép không thêm đường', b: '🧃 Nước ép không thêm đường' },
        { a: '🍵 Trà xanh không đường', b: '🍵 Trà xanh không đường' },
      ],
    },
    // Ngày 14 — Energy Tracker: chọn mức tỉnh táo.
    tracker: {
      title: 'Ngày 14: Energy Tracker',
      intro: 'Sau 2 tuần bớt ngọt, hôm nay bạn thấy mình tỉnh táo cỡ nào? Lắng nghe cơ thể một chút nhé.',
      prompt: 'Chọn mức cảm nhận của bạn',
      submit: 'Ghi nhận cảm nhận',
      success: 'Đã ghi nhận! Chú ý tới năng lượng của mình là kỹ năng bạn giữ được sau hành trình.',
      levels: [
        { emoji: '😵', label: 'Còn uể oải' },
        { emoji: '😐', label: 'Bình thường' },
        { emoji: '🙂', label: 'Nhẹ nhõm hơn' },
        { emoji: '😄', label: 'Tỉnh táo rõ' },
        { emoji: '⚡', label: 'Tràn năng lượng' },
      ],
    },
    // Ngày 19 — Vòng Quay May Mắn.
    spin: {
      title: 'Ngày 19: Vòng Quay May Mắn',
      intro: 'Quay vòng nhận buff điểm ngẫu nhiên, tiếp sức trước ngày về đích!',
      spin: 'Quay!',
      spinning: 'Đang quay…',
      result: (pts: number) => `Vòng quay dừng ở +${pts} điểm buff!`,
      success: 'Nạp năng lượng xong — tiến thẳng tới Đỉnh 0%!',
      segments: [10, 15, 20, 25, 30],
    },
    // Ngày 16 — Gumi Bắt Chữ (crossword ô lồng nhau): điền từ khoá theo gợi ý ngang/dọc, trong 3 phút.
    // grid toạ độ 1-index (r,c); các ô giao nhau đã kiểm tra khớp chữ. Bảng 15×15 (chỉ ô của từ mới hiện).
    crossword: {
      title: 'Ngày 16: Gumi Bắt Chữ',
      subtitle: 'Xoá Xổ Đường Dư',
      intro: 'Bấm vào ô rồi gõ thẳng chữ (bàn phím máy tính hoặc điện thoại) — gõ xong tự nhảy ô kế. Bấm gợi ý để tới nhanh. Bạn có 3 phút!',
      tapDir: 'Bấm lại ô để đổi hướng ngang ↔ dọc.',
      acrossLabel: 'Hàng ngang',
      downLabel: 'Hàng dọc',
      success: 'Xoá sổ đường dư! Bạn đã điền đúng cả ô chữ.',
      timeUp: (n: number, total: number) => `Hết 3 phút — bạn giải được ${n}/${total} từ. Cửa ải tính giờ không cho chơi lại nhé!`,
      rows: 15,
      cols: 15,
      words: [
        { num: 1, dir: 'down' as const,   r: 1,  c: 6,  answer: 'TRAICAY',    clue: 'Nên ăn cả quả thay vì ép lấy nước để giữ chất xơ' },
        { num: 2, dir: 'down' as const,   r: 1,  c: 9,  answer: 'SIRO',       clue: 'Chất lỏng ngọt sánh hay được bơm thêm vào đồ uống' },
        { num: 3, dir: 'across' as const, r: 3,  c: 5,  answer: 'CALORONG',   clue: 'Calo ___: chỉ có năng lượng từ đường, không dưỡng chất' },
        { num: 4, dir: 'down' as const,   r: 3,  c: 12, answer: 'GANNHIEMMO', clue: 'Hệ quả khi đường/mỡ thừa tích tụ ở gan (3 chữ)' },
        { num: 5, dir: 'across' as const, r: 5,  c: 1,  answer: 'VIGIAC',     clue: 'Khả năng cảm nhận vị trên lưỡi, nhạy hơn khi bớt ngọt' },
        { num: 6, dir: 'across' as const, r: 6,  c: 8,  answer: 'THEMNGOT',   clue: 'Cơn "nghiện" đồ ngọt khi đã quen ăn nhiều đường' },
        { num: 7, dir: 'down' as const,   r: 9,  c: 8,  answer: 'DUONGAN',    clue: 'Đường kính trắng cho vào cà phê, nấu ăn hằng ngày' },
        { num: 8, dir: 'across' as const, r: 12, c: 6,  answer: 'TINHTAO',    clue: 'Đầu óc minh mẫn, không lờ đờ khi tránh được sugar crash' },
      ],
    },
    // Ngày 21 — Giải Cứu Mèo Gumi: trượt mèo chắn đường để mèo chính thoát ra cửa phải (kiểu Rush Hour).
    slide: {
      title: 'Ngày 21: Giải Cứu Mèo Gumi',
      intro: 'Cửa ải cuối! Trượt các bé mèo chắn lối để mèo Gumi (mèo trắng) thoát ra cửa bên phải.',
      moves: (n: number) => `${n} bước`,
      level: (a: number, b: number) => `Màn ${a}/${b}`,
      hint: 'Kéo mèo dọc theo thân để trượt.',
      reset: 'Chơi lại màn',
      toMessage: 'Viết lời nhắn tốt nghiệp →',
      success: 'Gumi thoát ra ngoài, tiến hoá thành Chiến Thần 0% đường 🎉',
    },
    // Ngày 7, 16, 17 — trắc nghiệm nhanh (chung một màn QuickQuiz).
    quiz: {
      intro: 'Chọn đáp án đúng cho mỗi câu. Trả lời nhanh nào!',
      questionOf: (i: number, total: number) => `Câu ${i}/${total}`,
      wrong: 'Chưa đúng, thử lại nhé!',
      days: {
        7: {
          title: 'Ngày 7: Trắc Nghiệm Chớp Nhoáng',
          note: 'Giảm đường từ từ, cơ thể sẽ cảm ơn bạn: tim khoẻ hơn, đầu óc tỉnh táo hơn, da cũng đẹp hơn 💪',
          questions: [
            { prompt: 'Theo WHO, lượng đường tự do (free sugar) khuyến nghị tối đa cho một người trưởng thành mỗi ngày là bao nhiêu?', options: ['15g (≈ 3 thìa cà phê)', '25g (≈ 5–6 thìa cà phê)', '50g (≈ 10–12 thìa cà phê)', 'Càng nhiều càng tốt'], answer: 1, explain: 'WHO khuyến nghị giới hạn dưới 25g/ngày (≈ 5% tổng năng lượng) để tốt nhất cho tim mạch và cân nặng.' },
            { prompt: 'Khi bắt đầu giảm đường, quy tắc nào giúp vị giác thích nghi mà không thèm ngọt cồn cào?', options: ['Nhịn ngọt tuyệt đối 100% ngay ngày đầu', 'Hạ dần từng nấc (100% → 70% → 50% → 30%) trong 2–3 tuần', 'Uống nước ngọt thay nước lọc', 'Uống trà sữa lúc đêm muộn'], answer: 1, explain: 'Gai vị giác cần ~2–3 tuần để làm quen độ nhạt mới; giảm đột ngột dễ gây stress và ăn bù.' },
            { prompt: 'Cảm giác hưng phấn sau khi uống trà sữa rồi bỗng mệt mỏi, buồn ngủ lờ đờ sau 1–2 tiếng gọi là gì?', options: ['Say caffeine', 'Tụt đường huyết (Sugar Crash)', 'Trúng thực nhẹ', 'Thiếu oxy não'], answer: 1, explain: 'Đường lỏng làm đường huyết tăng vọt, cơ thể tiết nhiều insulin để hạ nên đường huyết tụt nhanh, gây mệt.' },
          ],
        },
        16: {
          title: 'Ngày 16: Đuổi Hình Bắt Chữ · Vòng 2',
          note: 'Giải nhanh chuỗi emoji thành tên đồ uống nhiều đường.',
          questions: [
            { prompt: '🧋🟤🟤🟤', options: ['Trà sữa trân châu', 'Nước lọc', 'Cà phê đen'], answer: 0, explain: '🧋 + trân châu = ly nhiều đường bậc nhất.' },
            { prompt: '🥤🍋 ➕ 🍬', options: ['Trà mộc', 'Soda chanh ngọt', 'Trà xanh không đường'], answer: 1, explain: 'Nước có ga + siro chanh = lượng đường ẩn khá cao.' },
            { prompt: '🧊☕️🍮', options: ['Cà phê không đường', 'Bạc xỉu / cà phê caramel', 'Nước dừa tươi'], answer: 1, explain: 'Cà phê nhiều sữa đặc + caramel rất ngọt.' },
          ],
        },
        17: {
          title: 'Ngày 17: Truy Tìm Sự Thật',
          note: 'Nhớ nha: đường "ẩn" có mặt ở cả đồ mặn — đọc nhãn trước khi mua là bạn đã thắng một nửa rồi! 🔍',
          questions: [
            { prompt: 'Nước ép trái cây đóng chai luôn "healthy" và ít đường.', options: ['Đúng', 'Sai'], answer: 1, explain: 'Nhiều loại nước ép đóng chai được thêm đường, không hề ít.' },
            { prompt: 'Đường "ẩn" có thể xuất hiện cả trong đồ mặn như nước sốt, bánh mì.', options: ['Đúng', 'Sai'], answer: 0, explain: 'Đúng — nước sốt, bánh mì, đồ hộp đều có thể chứa đường.' },
            { prompt: 'Uống nhiều đường một lúc có thể gây tụt năng lượng sau đó (sugar crash).', options: ['Đúng', 'Sai'], answer: 0, explain: 'Đường huyết tăng vọt rồi tụt nhanh khiến mệt và thèm ngọt tiếp.' },
            { prompt: 'Đồ uống dán nhãn "không đường" chắc chắn không có chất tạo ngọt nào.', options: ['Đúng', 'Sai'], answer: 1, explain: '"Không đường" vẫn có thể dùng chất tạo ngọt thay thế.' },
            { prompt: 'Giảm đường từ từ giúp vị giác quen dần và dễ duy trì hơn.', options: ['Đúng', 'Sai'], answer: 0, explain: 'Giảm dần dễ theo hơn là cắt đột ngột.' },
          ],
        },
      },
    },
  },

  wall: {
    title: 'Ngày 21: Lời Nhắn Tốt Nghiệp',
    formPrompt: 'Viết một câu về việc cơ thể hoặc vị giác của bạn đã thay đổi ra sao sau 21 ngày.',
    placeholder: 'Ví dụ: Mình thấy nước lọc ngọt hơn và ngủ ngon hơn hẳn…',
    hint: '10–200 ký tự.',
    tooShort: 'Lời nhắn cần ít nhất 10 ký tự.',
    submit: 'Gửi lên bức tường',
    postedTitle: 'Đã gửi! Cảm ơn bạn đã đồng hành.',
    postedSub: 'Lời nhắn của bạn đã lên Bức tường cộng đồng Gumi.',
    wallTitle: 'Bức tường cộng đồng',
    empty: 'Chưa có lời nhắn nào. Hãy là người đầu tiên tốt nghiệp!',
    notToday: 'Bức tường tốt nghiệp mở vào Ngày 21.',
    viewCard: 'Xem card Sugar Journey',
    posts: [] as { name: string; text: string }[],
  },
  summary: {
    title: 'Sugar Journey của bạn',
    graduated: '🎉 TỐT NGHIỆP 21 NGÀY BỚT NGỌT!',
    evolveCaption: 'Gumi đã tiến hoá: Sugar Master — Chiến thần 0% đường',
    metrics: {
      sugarCut: 'Đường đã cắt giảm',
      grams: (g: number) => `≈ ${g} g`,
      spoons: (n: number) => `≈ ${n} thìa`,
      lowest: 'Mức đường thấp nhất chinh phục',
      healthy: 'Ly healthy đã check-in',
      quiz: 'Thần đồng Sugar Quiz',
      streak: 'Chuỗi ngày kiên trì',
    },
    totalPoints: 'Tổng điểm', rank: 'Hạng chung cuộc',
    provisional: 'Hạng tạm tính — bảng chốt sau khi hết chiến dịch.',
    final: 'Hạng chung cuộc đã chốt.',
    notEligible: 'Bạn cần hoàn thành đủ Ngày 21 để nhận card Sugar Journey.',
    share: 'Chia sẻ Story · IG · FB',
    downloadImage: 'Tải ảnh',
    facebook: 'Facebook',
    building: 'Đang tạo ảnh…',
    shared: 'Đã mở bảng chia sẻ — chọn Instagram / Facebook để đăng nhé!',
    downloaded: 'Đã tải ảnh! Đăng lên Story Instagram / Facebook của bạn nhé.',
    shareError: 'Chưa tạo được ảnh, thử lại nhé.',
    shareNote: 'Trên điện thoại sẽ mở thẳng Instagram / Facebook; trên máy tính ảnh được tải về để bạn đăng.',
    backHome: 'Về hành trình',
  },
  admin: {
    title: 'Quản trị chiến dịch',
    tabStats: 'Thống kê', tabByDay: 'Theo ngày', tabByUser: 'Theo người', tabFlags: 'Ảnh bị báo cáo',
    stats: {
      title: 'Tổng quan người chơi',
      totalPlayers: 'Người tham gia',
      activePlayers: 'Đang chơi',
      eligible: 'Đạt chỉ tiêu',
      eligibleHint: 'Hoàn thành từ 14/21 ngày',
      finished: 'Về đích 21 ngày',
      avgPoints: 'Điểm trung bình',
      avgDays: 'Ngày TB đã làm',
      pending: 'Ảnh chờ duyệt',
      tableTitle: 'Danh sách người chơi',
      colPlayer: 'Người chơi', colDays: 'Ngày', colPoints: 'Điểm', colStatus: 'Trạng thái',
      badgeFinished: 'Về đích', badgeEligible: 'Đạt chỉ tiêu', badgeActive: 'Đang chơi', badgeIdle: 'Chưa bắt đầu',
      usedPass: 'Đã dùng vé',
    },
    day: (n: number) => `Ngày ${n}`,
    approved: 'Đã duyệt', rejected: 'Đã gỡ', pending: 'Chờ',
    view: 'Xem', approve: 'Duyệt', reject: 'Gỡ ảnh',
    rejectTitle: 'Gỡ ảnh này?',
    rejectBody: 'Người chơi sẽ mất điểm ngày này và điểm, chuỗi được tính lại. Chọn lý do:',
    reasons: ['Ảnh không phải ly nước', 'Ảnh trùng ngày khác', 'Ảnh không rõ / không liên quan', 'Nghi ngờ chỉnh sửa'],
    confirmReject: 'Xác nhận gỡ', cancel: 'Huỷ',
    flagQueue: 'Hàng chờ ảnh bị báo cáo',
    flagReason: (r: string) => `Lý do báo cáo: ${r}`,
    empty: 'Không có ảnh nào cần duyệt.',
    forbiddenTitle: 'Không có quyền',
    forbidden: 'Trang này chỉ dành cho ban tổ chức. Nếu bạn nghĩ đây là nhầm lẫn, hãy liên hệ quản trị.',
  },
  errors: {
    notFoundTitle: 'Không tìm thấy trang',
    notFound: 'Đường dẫn này không tồn tại hoặc đã đổi. Hãy về hành trình của bạn.',
    offlineTitle: 'Mất kết nối',
    offline: 'Có vẻ bạn đang ngoại tuyến. Kiểm tra mạng rồi thử lại nhé.',
    maintenanceTitle: 'Đang bảo trì',
    maintenance: 'Gumi đang được chăm sóc một chút. Bạn quay lại sau ít phút nhé!',
    serverTitle: 'Có lỗi từ máy chủ',
    server: 'Máy chủ đang gặp sự cố. Việc của bạn không mất, hãy thử lại sau giây lát.',
    retry: 'Thử lại', home: 'Về hành trình',
  },
  toast: { success: 'Thành công', error: 'Có lỗi', info: 'Thông tin' },
  pwa: {
    install: 'Cài app',
    title: 'Cài Level Down lên điện thoại',
    tabIos: 'iPhone',
    tabAndroid: 'Android',
    iosTitle: 'Cài Level Down lên iPhone',
    iosNote: 'iPhone không cho cài tự động — làm 3 bước sau (phải mở bằng Safari; Chrome/Cốc Cốc không cài được):',
    iosSteps: [
      'Bấm nút Chia sẻ ⬆️ ở thanh Safari.',
      'Kéo xuống, chọn "Thêm vào Màn hình chính".',
      'Bấm "Thêm" — xong, icon hiện ở màn hình chính!',
    ],
    androidTitle: 'Cài Level Down lên Android',
    androidNote: 'Mở bằng Chrome rồi làm 3 bước sau (thường chỉ mất 5 giây):',
    androidSteps: [
      'Bấm nút menu ⋮ ở góc trên bên phải Chrome.',
      'Chọn "Cài đặt ứng dụng" (hoặc "Thêm vào Màn hình chính").',
      'Bấm "Cài đặt" — icon hiện ở màn hình chính!',
    ],
    close: 'Đã hiểu',
  },
} as const;

export type MissionKind = 'DRINK' | 'KNOW' | 'SHARE' | 'GAME' | 'TRACKER' | 'FINAL';
